name: Shellcheck Validation

on:
  issue_comment:
    types: [created, edited]
  # optional – lets you run it from the “Actions” tab while debugging
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write

jobs:
  shellcheck:
    if: github.event.issue.pull_request &&
        (contains(github.event.comment.body, '/check-shellcheck') ||
         contains(github.event.comment.body, '/check-all'))
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Get PR details
      id: pr
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          return {
            ref: pullRequest.head.ref,
            sha: pullRequest.head.sha
          };
    
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ fromJson(steps.pr.outputs.result).ref }}
        fetch-depth: 0
    
    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    
    - name: Run shellcheck on try-them-all-isa.sh
      id: shellcheck
      run: |
        echo "Running shellcheck on try-them-all-isa.sh..."
        if shellcheck try-them-all-isa.sh; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "message=✅ Shellcheck passed for try-them-all-isa.sh" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "message=❌ Shellcheck failed for try-them-all-isa.sh" >> $GITHUB_OUTPUT
          exit 1
        fi
    
    - name: Update commit status
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const state = '${{ steps.shellcheck.outputs.status }}' === 'success' ? 'success' : 'failure';
          const description = '${{ steps.shellcheck.outputs.message }}';
          
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: '${{ fromJson(steps.pr.outputs.result).sha }}',
            state: state,
            target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            description: description,
            context: 'shellcheck/try-them-all-isa'
          });
    
    - name: Comment on PR
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const state = '${{ steps.shellcheck.outputs.status }}';
          const message = '${{ steps.shellcheck.outputs.message }}';
          
          const body = state === 'success' 
            ? `${message}\n\nThe shellcheck validation has passed. ✅`
            : `${message}\n\nPlease fix the shellcheck issues before merging. ❌`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: body
          });
